### ISSUE TITLE
how ot use the code

### ISSUE THREAD

**Issue by Abd2z** [PuchatekwSzortach/face_detection#2]
Thank you for sharing the work. However it would be good if you could give some  demo examples how to use the code.
I tried my best but unfortunately  didn't succeed.

your help is appreciated

**Comment by PuchatekwSzortach** [comment]
@GooFace2 Files in `scripts` folder are the very same code I use to run the software.
Typically one would call them in this order:
1. scripts/download_data.py - to download the data
2. scripts/train_model.py - to train a model
3. scripts/visualization.py - to visualize results
4. scripts/accuracy.py - to compute model accuracy

Probably main points to be aware of are that data download directory is defined in `face.config` file and that download links might be dead - I don't maintain them. 
If you have any specific questions, feel free to ask and I'll try to answer them.

**Comment by PuchatekwSzortach** [comment]
@GooFace2 Do you still have any questions? If not, I'll be closing this issue shortly.

**Comment by PuchatekwSzortach** [comment]
Closing due to lack of user input.
